### ISSUE TITLE
The request failed with unexpected status code 'Forbidden'

### ISSUE THREAD

**Issue by felixfbecker** [tintoy/dotnet-kube-client#20]
First of all, thank you for this library! I totally agree with the design philosophy and the API feels so much more ergonomic than the official client.

I tried it to get all pods in a `kubectl get pods` fashion (using `~/.kube/config`):

```csharp
K8sConfig config = K8sConfig.Load();
KubeClientOptions clientOptions = config.ToKubeClientOptions(
    defaultKubeNamespace: "default"
);
clientOptions.LogHeaders = true;
clientOptions.LogPayloads = true;
var loggerFactory = new LoggerFactory();
loggerFactory.AddFile("test.log", LogLevel.Trace);
client = KubeApiClient.Create(clientOptions, loggerFactory);
```

but I always get this error:

```
HTTPlease.HttpRequestException`1[KubeClient.Models.StatusV1]: The request failed with unexpected status code 'Forbidden'.
   at HTTPlease.FormatterResponseExtensions.ReadContentAsAsync[TBody,TError](HttpResponseMessage responseMessage, HttpStatusCode[] successStatusCodes)
   at KubeClient.ResourceClients.KubeResourceClient.GetResourceList[TResourceList](HttpRequest request, CancellationToken cancellationToken)
   at KubeClient.ResourceClients.PodClientV1.List(String labelSelector, String kubeNamespace, CancellationToken cancellationToken)
   at Kubectl.GetKubePodCmdlet.ProcessRecord() in /Users/felix/src/github.com/felixfbecker/PSKubectl/src/GetKubePodCmdlet.cs:line 23
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

The cluster is hosted on Google Kubernetes Engine.
`kubectl get pods` lists the pods successfully.

These are the logs:
```
2018-08-16T17:07:16.9259220+02:00  [DBG] Performing "GET" request to 'https://35.202.230.255/api/v1/namespaces/default/pods'. (cd91936f)
2018-08-16T17:07:18.8543420+02:00  [DBG] Receive response body for "GET" request to 'https://35.202.230.255/api/v1/namespaces/default/pods' (Forbidden):
"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods is forbidden: User \\"system:anonymous\\" cannot list pods in the namespace \\"default\\": No policy matched.\nUnknown user \\"system:anonymous\\"\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"pods\"},\"code\":403}
" (29add6de)
2018-08-16T17:07:18.8547270+02:00  [DBG] Completed "GET" request to 'https://35.202.230.255/api/v1/namespaces/default/pods' (Forbidden). (be205803)
```

Any idea why `kubectl get pods` works but KubeClient fails?

**Comment by tintoy** [comment]
Hi :)
What sort of authentication is specified in your kube config? There's a chance that GKE may be using the new "script"-style authentication mechanism (which I haven't added support for yet).

**Comment by felixfbecker** [comment]
I posted the relevant section of the yaml in the issue, seems like it uses what you mean. Is support for it planned?

**Comment by tintoy** [comment]
It is now :)

**Comment by tintoy** [comment]
Oh, and sorry I've been reading this on my phone which is why I missed the config yaml before :)

**Comment by tintoy** [comment]
Ok - I'm going to see what's required to implement it this morning; I was hoping to get some ideas from the official client but it looks like they don't support exec-based authentication either yet. Hopefully it should be relatively easy to implement though 😄

**Comment by tintoy** [comment]
GCP authentication seems to be something specific but there's a Go implementation I think I can reverse-engineer:

https://github.com/kubernetes/client-go/blob/fb6075f2e0b094320f3d2c3e99add90a4661fcff/plugin/pkg/client/auth/gcp/gcp.go

**Comment by tintoy** [comment]
The official K8s client for C# currently suggests using [kubectl proxy](https://github.com/kubernetes-client/csharp/pull/92/files) but I think we _might_ be able to do better in the long run. I don't currently have a GCP cluster running so I can't test this yet but if you have a moment would you mind trying the linked workaround just so I know if the authentication is the only thing stopping us from connecting to GCP?

**Comment by tintoy** [comment]
In the meanwhile I'll start sketching out a mechanism for authentication plugins (and implementing the GCP authentication plugin which doesn't seem all that complex, except perhaps for their use of Go-style field selector syntax such as `{.token}` which we may be able to fudge).

**Comment by felixfbecker** [comment]
Yeah I was hoping we could do better than that - I'm trying to reimplement kubectl in PowerShell, so it would be nice if kubectl didn't have to be used in the background to get it working.

When I try to connect to GKE through kubectl proxy, I get the error "Empty response body". However, when I try to use Postman or curl, the response body is in fact empty, so I don't think this is a bug in KubeClient. kubectl proxy logs this every time:
```
I0818 00:48:45.712346   67980 logs.go:41] http: proxy error: net/http: TLS handshake timeout
```
It might just be because I'm tethering over LTE.

**Comment by tintoy** [comment]
I like the PS idea :)

That empty response body seems vaguely familiar - I might try digging through my mailbox to see if I can find anything.

**Comment by tintoy** [comment]
I assume `kubectl get pods` still works against gcp?

**Comment by tintoy** [comment]
Agh, again sorry you did say - I need to stop reading issues on my phone!

**Comment by tintoy** [comment]
Ok, as long as `kubectl` uses the command-style token provider (which from the look of your config YAML it already does), it should be pretty simple to support this (the Google-specific authentication mechanism may take a little longer so I'll probably focus on the simple case for now).

**Comment by tintoy** [comment]
I'll have a go at building out something tomorrow (Sunday AEST) and I'll post updates here in case you want to try a preview build :)

**Comment by tintoy** [comment]
BTW, if you're doing async stuff in a Cmdlet, you might find this useful:

https://github.com/DimensionDataResearch/cloudcontrol-powershell-core/blob/develop/src/DD.CloudControl.Powershell/AsyncCmdlet.cs
https://github.com/DimensionDataResearch/cloudcontrol-powershell-core/blob/develop/src/DD.CloudControl.Powershell/Utilities/ThreadAffinitiveSynchronizationContext.cs

(apologies if you've already worked this out, but it took me a while to get it right)

**Comment by felixfbecker** [comment]
The thing I can’t figure out is how to hook the LoggerFactory up to WriteVerbose/Information/Debug/Warning, since those methods are only allowed to be called on the main thread from within Process methods

**Comment by tintoy** [comment]
Yeah, slightly painful that one - the short answer is that if you expose the `ThreadAffinitiveSynchronizationContext` (or equivalent) used while running the async method, then anything from any thread can call `SynchronizationContext.Post` with a delegate and that delegate will be executed on the main thread

**Comment by felixfbecker** [comment]
Ah, so I could use that to make sure the Write calls of the logger get executed on the main thread, and then I only need to ignore them while no Process method is active.

**Comment by tintoy** [comment]
Yep - just check if `SynchonizationContext.Current is ThreadAffinitiveSynchronizationContext`

**Comment by felixfbecker** [comment]
I can confirm that it works with `kubectl proxy` on stable WiFi :)

**Comment by tintoy** [comment]
@felixfbecker I'm about to start work on this - would you be up for trying it out once I've got something working?

**Comment by tintoy** [comment]
Ok - I've tried the new code in the [`feature/auth-cmd`](https://github.com/tintoy/dotnet-kube-client/tree/feature/auth-cmd) branch against GKE and it works! If you have a moment, would you mind trying it for yourself to see if it works for you?

In the meanwhile I'll see what I can do about using the existing cached token, if present in `~/.kube/config`.

**Comment by tintoy** [comment]
Ok, this should be working now in the latest release :)

Feel free to reopen if it doesn't work for you.
