### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException when listing pods

### ISSUE THREAD

**Issue by felixfbecker** [tintoy/dotnet-kube-client#21]
I am trying to connect to a Docker-for-mac Kubernetes server behind `kubectl proxy`.

When listing pods, I get this error:
```
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'KubeClient.Models.PodListV1' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'kind', line 1, position 8.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(TextReader reader, Type objectType)
   at HTTPlease.Formatters.Json.JsonFormatter.ReadAsync(InputFormatterContext context, Stream stream)
   at HTTPlease.Formatters.ContentExtensions.ReadAsAsync[TBody](HttpContent content, IInputFormatter formatter, InputFormatterContext formatterContext)
   at HTTPlease.FormatterResponseExtensions.ReadContentAsAsync[TBody](HttpResponseMessage responseMessage, IInputFormatter formatter, InputFormatterContext formatterContext)
   at HTTPlease.FormatterResponseExtensions.ReadContentAsAsync[TBody](HttpResponseMessage responseMessage, IFormatterCollection formatters)
   at HTTPlease.FormatterResponseExtensions.ReadContentAsAsync[TBody](HttpResponseMessage responseMessage)
   at KubeClient.ResourceClients.KubeResourceClient.GetResourceList[TResourceList](HttpRequest request, CancellationToken cancellationToken)
   at KubeClient.ResourceClients.PodClientV1.List(String labelSelector, String kubeNamespace, CancellationToken cancellationToken)
   at Kubectl.GetKubePodCmdlet.ProcessRecord() in /Users/felix/src/github.com/felixfbecker/PSKubectl/src/GetKubePodCmdlet.cs:line 25
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

Logs:
```
2018-08-16T19:28:42.7170010+02:00  [DBG] Performing "GET" request to 'http://127.0.0.1:8001/api/v1/namespaces/default/pods'. (cd91936f)
2018-08-16T19:28:42.7239570+02:00  [DBG] Receive response body for "GET" request to 'http://127.0.0.1:8001/api/v1/namespaces/default/pods' (OK):
"{\"kind\":\"PodList\",\"apiVersion\":\"v1\",\"metadata\":{\"selfLink\":\"/api/v1/namespaces/default/pods\",\"resourceVersion\":\"699\"},\"items\":[]}
" (29add6de)
2018-08-16T19:28:42.7240110+02:00  [DBG] Completed "GET" request to 'http://127.0.0.1:8001/api/v1/namespaces/default/pods' (OK). (be205803)
```

When manually requesting `http://127.0.0.1:8001/api/v1/namespaces/default/pods` with Postman, I get this response:
```json
{
    "kind": "PodList",
    "apiVersion": "v1",
    "metadata": {
        "selfLink": "/api/v1/namespaces/default/pods",
        "resourceVersion": "520"
    },
    "items": []
}
```

**Comment by tintoy** [comment]
Hi - thanks for the detailed report! I'll have a look at this first thing tomorrow morning (sorry for the delay; I'm in Australia, and won't get home from work until quite late tonight).

**Comment by tintoy** [comment]
Ok, this is weird - this used to work but seems to be broken for me on current Docker-for-Windows K8s. I'll look into this before I tackle the authentication scheme stuff...

**Comment by tintoy** [comment]
Ah, sorry, it looks like a recent change has caused this behaviour - I'll publish a new build shortly!

**Comment by tintoy** [comment]
Ok, @felixfbecker - can you give v2.1.6 a try? I've tested it locally against Docker-for-Windows and this works correctly now.

NuGet may take a while to index the new packages but they'll be available immediately on MyGet (add the feed `https://www.myget.org/F/dotnet-kube-client/api/v3/index.json` to `NuGet.config`).

**Comment by tintoy** [comment]
(sorry about that, I obviously need to add more tests for serialisation!)

**Comment by felixfbecker** [comment]
Works, thanks for the quick fix!
